In [2]:
import numpy as np

# 대칭행렬을 랜크-1 행렬의 합으로 분해
### data science school pg 201~204
~~~
N차원 대칭행렬 A는 다음처럼 N개의 랭크-1 행렬을 아래 식의 합으로 표시 가능
~~~
$A_i$ = np.dot($V_i$, $V_i$.T)

In [5]:
A=np.array([[60, 30, 20], [30, 20, 15], [20, 15, 12]])

w, V=np.linalg.eig(A)   #고윳값과 고유벡터를 순서대로 return (고윳값:, 고유벡터: )
w1, w2, w3=w            #고윳값
v1=V[:, 0:1]
v2=V[:, 1:2]
v3=V[:, 2:3]

A1=v1@v1.T
A2=v2@v2.T
A3=v3@v3.T

print("고윳값 w:", w)

고윳값 w: [84.49913563  7.33962395  0.16124042]


In [8]:
print('고윳값_1과 v1 @ v1.T를 내적한 결과:\n',w1*A1)

고윳값_1과 v1 @ v1.T를 내적한 결과:
 [[57.79768857 32.13739648 22.59357583]
 [32.13739648 17.8694387  12.56276371]
 [22.59357583 12.56276371  8.83200836]]


In [9]:
print("고윳값_2과 v2 @ v2.T를 내적한 결과:\n", w2*A2)

고윳값_1과 v2 @ v2.T를 내적한 결과:
 [[ 2.19968372 -2.12270483 -2.60775134]
 [-2.12270483  2.04841985  2.51649195]
 [-2.60775134  2.51649195  3.09152039]]


In [10]:
print("고윳값_3과 v3 @ v3.T를 내적한 결과:\n", w3*A3)

고윳값_3과 v3 @ v3.T를 내적한 결과:
 [[ 0.00262772 -0.01469165  0.01417551]
 [-0.01469165  0.08214145 -0.07925566]
 [ 0.01417551 -0.07925566  0.07647125]]


In [11]:
print('A의 값을 구하기:')
w1*A1+w2*A2+w3*A3

A의 값을 구하기:


array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

### 만약 0인 고윳값이 없다면 역행렬도 다음처럼 N개의 랭크-1 행렬의 합으로 표시할 수 있음
$A_i$ = np.dot($V_i$, $V_i$.T)

In [12]:
np.linalg.inv(A)       #np.linalg.inv는 역행렬을 계산하는 함수이다

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [13]:
1/w1*A1+1/w2*A2+1/w3*A3    #역수들을 이용해서 계산하면 역행렬을 계산한 것과 같은 결과

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])