In [1]:
import numpy as np

# 선형종속과 선형 독립
### data science school pg 164~
* 선형종속: 선형조합이 0이되게 만들기 위한 벡터의 계수가 모두 0인 경우 제외한 계수 벡터가 존재
* 선형독립: 벡터의 계수가 모두 0인 경우에면 선형조합이 0이 됨.

In [2]:
x1=np.array([1, 2])
x2=np.array([3, 3])
x3=np.array([10, 14])
2*x1+x2-0.5*x3        #계수가 모두 0이 아니여도 선형조합이 0인 결과 나타남 (x1, x2, x3은 선형종속이다.)

array([0., 0.])

## 랭크
### data science school pg 168~170
* 열랭크(column rank): 열벡터 중 서로 독립인 열벡터의 최대 개수
* 행랭크(row rank): 행벡터 중 서로 독립인 행벡터의 최대 개수

**행랭크와 열랭크는 항상 같다**
~~~
모든 열벡터들이 선형독립일 경우 열벡터의 개수와 열랭크의 개수가 동일하다
하지만 열벡터가 선형종속일 경우 열랭크는 열벡터의 개수보다 작다.

numpy의 linalg 서브 패키지의 matrix_rank() 함수로 행렬의 랭크 계산 가능
~~~

In [4]:
x_1=np.array([[1, 3], [2, 4]])
np.linalg.matrix_rank(x_1)       #행렬의 랭크를 계산하는 함수 사용

2

In [5]:
x_2=np.array([[1, 3, 5], [2, 3, 7]])
np.linalg.matrix_rank(x_2) 

2

### 연습문재 3.2.4

**a의 랭크를 구하여라**
~~~
풀이: 첫번째와 두번째 열벡터는 서로 독립이나 세번째 벡터는 1, 2번째 벡터의 합과 같으므로 종속이다
~~~

In [7]:
a=np.array([[1, 5, 6], [2, 6, 8], [3, 11, 14], [1, 4, 5]])
np.linalg.matrix_rank(a)

2

### 연습문제 3.2.5

**1) 다음 벡터로 랭크-1 행렬을 만들고 넘파이로 랭크를 계산하여 실제로 1이 나오는지 확인해라**
~~~
x1=np.array([[1], [1]])
~~~
**2) 다음 두 개의 벡터로 랭크-2 행렬을 만들고 넘파이로 랭크를 계산하여 실제로 2가 나오는지 확인하라**
~~~
x1=np.array([[1], [1]])
x2=np.array([[1], [-1]])
~~~

In [8]:
x1=np.array([[1], [1]])
m1=x1@x1.T
m1

array([[1, 1],
       [1, 1]])

In [9]:
np.linalg.matrix_rank(m1)    #랭크-1 행렬의 랭크는 1이다

1

#### 랭크-2 행렬
~~~
x1 @ x1.T + x2 @ x2.T
~~~

In [11]:
x1=np.array([[1], [1]])
x2=np.array([[1], [-1]])
print('np.hstack([x1, x2]):', np.hstack([x1, x2]))
print('np.vstack([x1.T, x2.T]):' , np.vstack([x1.T, x2.T]))

np.hstack([x1, x2]): [[ 1  1]
 [ 1 -1]]
np.vstack([x1.T, x2.T]): [[ 1  1]
 [ 1 -1]]


In [12]:
m2=np.hstack([x1, x2])@np.vstack([x1.T, x2.T])
m2

array([[2, 0],
       [0, 2]])

In [13]:
np.linalg.matrix_rank(m2)   #랭크-2의 행렬의 랭크는 2이다

2