# 파이썬을 이용한 특잇값 분해
### data science study pg 213~215
~~~
정방행령이 아닌 경우 고유분해(고윳값과 고유벡터 찾기)가 불가능하므로 특잇값분해를 한다.
~~~

In [2]:
from numpy.linalg import svd
import numpy as np

In [3]:
A=np.array([[3, -1], [1, 3], [1, 1]])
U, S, VT=svd(A)

In [4]:
U                        #왼쪽 특이벡터: 정방행렬(행과 열의 수가 동일), 모든 열벡터가 단위벡터, 서로 직교

array([[-4.08248290e-01,  8.94427191e-01, -1.82574186e-01],
       [-8.16496581e-01, -4.47213595e-01, -3.65148372e-01],
       [-4.08248290e-01, -2.65251338e-16,  9.12870929e-01]])

In [5]:
S                                

array([3.46410162, 3.16227766])

In [6]:
np.diag(S, 1)[:, 1:]      # 특잇값: 대각행렬, 큰 수부터 순서대로 배열

array([[3.46410162, 0.        ],
       [0.        , 3.16227766],
       [0.        , 0.        ]])

In [7]:
VT                        #오른쪽 특이벡터: 정방행렬(행과 열의 수가 동일), 모든 열벡타기 단위벡터, 서로 직교

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [8]:
U@np.diag(S, 1)[:, 1:]@VT

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

### 축소형을 구하기 위해서 인수 full_matrices=False로 지정

In [9]:
U2, S2, VT2=svd(A, full_matrices=False)

In [10]:
U2                   #왼쪽 특이벡터: 

array([[-4.08248290e-01,  8.94427191e-01],
       [-8.16496581e-01, -4.47213595e-01],
       [-4.08248290e-01, -2.65251338e-16]])

In [11]:
S2                   #특잇값: 대각행렬(대각형으로 수 있고 나머지는 0)이고 큰수부터 작은수

array([3.46410162, 3.16227766])

In [12]:
VT2                 #오른쪽 특이벡터: 정방행렬(열=행 수), 단위벡터, 서로 직교

array([[-0.70710678, -0.70710678],
       [ 0.70710678, -0.70710678]])

In [13]:
U2@np.diag(S2)@VT2    #np.diag는 대각행렬 생성

array([[ 3., -1.],
       [ 1.,  3.],
       [ 1.,  1.]])

### 3.4.1 연습문제) 
~~~ 
넘파이를 사용하여 다음 행렬을 특잇값분해를 한다.(축소형이 아닌 방법과 축소형 방법을 각각 사용한다.) 또한 다시 곱해서 원래의 행렬이 나오는 것을 보여라

b=[[3, 2, 2], [2, 3, -2]], C=([[2, 4], [1, 3], [0, 0], [0, 0]])
~~~

In [14]:
b=np.array([[3, 2, 2], [2, 3, -2]])
c=np.array([[2, 4], [1, 3], [0, 0], [0, 0]])

In [16]:
#행렬의 SVD
U, S, VT=svd(b)

print('\nb'); print(b)
print('\nU'); print(U)                         #특이벡터: 정방행렬, 단위벡터, 직교
print('\nS'); print(np.diag(S, -1)[1:, :])     #특잇값: 대각행렬, 큰 수부터 작은수
print('\nV'); print(VT.T)                      #특이벡터: 정방행렬, 단위벡터, 직교
print('\nU S VT'); print(U@np.diag(S, -1)[1:, :]@VT)


b
[[ 3  2  2]
 [ 2  3 -2]]

U
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S
[[5. 0. 0.]
 [0. 3. 0.]]

V
[[-7.07106781e-01 -2.35702260e-01 -6.66666667e-01]
 [-7.07106781e-01  2.35702260e-01  6.66666667e-01]
 [ 1.34375929e-16 -9.42809042e-01  3.33333333e-01]]

U S VT
[[ 3.  2.  2.]
 [ 2.  3. -2.]]


In [17]:
#B 행렬의 축소형 SVD
U, S, VT=svd(b, full_matrices=False)

print('\nb'); print(b)
print('\nU'); print(U)             #특이벡터: 정방행렬(행 수=열 수), 직교, 단위벡터
print('\nS'); print(np.diag(S))    #특잇값: 대각행렬 만드는 함수(np.diag) 사용
print('\nV'); print(VT.T)          #특이벡터: 정방행렬(행 수=열 수), 직교, 단위벡터
print('\nU S VT'); print(U@np.diag(S)@VT)


b
[[ 3  2  2]
 [ 2  3 -2]]

U
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S
[[5. 0.]
 [0. 3.]]

V
[[-7.07106781e-01 -2.35702260e-01]
 [-7.07106781e-01  2.35702260e-01]
 [ 1.34375929e-16 -9.42809042e-01]]

U S VT
[[ 3.  2.  2.]
 [ 2.  3. -2.]]


In [18]:
#C 행렬의 SVD
U, S, VT=svd(c)

print('\nc'); print(c)
print('\nU'); print(U)
print('\nS'); print(np.diag(S, 2)[:, 2:])
print('\nV'); print(VT.T)
print('\nU S VT'); print(U@np.diag(S, 2)[:, 2:]@VT)


c
[[2 4]
 [1 3]
 [0 0]
 [0 0]]

U
[[-0.81741556 -0.57604844  0.          0.        ]
 [-0.57604844  0.81741556  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]

S
[[5.4649857  0.        ]
 [0.         0.36596619]
 [0.         0.        ]
 [0.         0.        ]]

V
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

U S VT
[[2. 4.]
 [1. 3.]
 [0. 0.]
 [0. 0.]]


In [19]:
#C 행렬의 축소형 SVD
U, S, VT=svd(c, full_matrices=False)

print('\nc'); print(c)
print('\nU'); print(U)
print('\nS'); print(np.diag(S))
print('\nV'); print(VT.T)
print('\nU S VT'); print(U@np.diag(S)@VT)


c
[[2 4]
 [1 3]
 [0 0]
 [0 0]]

U
[[-0.81741556 -0.57604844]
 [-0.57604844  0.81741556]
 [ 0.          0.        ]
 [ 0.          0.        ]]

S
[[5.4649857  0.        ]
 [0.         0.36596619]]

V
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

U S VT
[[2. 4.]
 [1. 3.]
 [0. 0.]
 [0. 0.]]
